#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


class ThriftAudioItem
  include ::Thrift::Struct, ::Thrift::Struct_Union
  UID = 1
  TITLE = 2

  FIELDS = {
    UID => {:type => ::Thrift::Types::STRING, :name => 'uid'},
    TITLE => {:type => ::Thrift::Types::STRING, :name => 'title', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
    raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field uid is unset!') unless @uid
  end

  ::Thrift::Struct.generate_accessors self
end

